### ISSUE TITLE
Scorecards feature

### ISSUE THREAD

**Issue by marcusradell** [salt-community/scorecard#27]

**Comment by Finns841594** [comment]
1. Turns Languages and Educations from string to object in the background section so they have such informations:

> - languages :
> 
> beginner, intermediary, fluent, native
> 
> - education :

> change it to academics
> degree type
> number of year studied
> school

2. Turns the 'skill' from string to object, change the frontend to display skills

3. Explaining 'Kyu', 'Performance' etc in the frontend

**Comment by Finns841594** [comment]
Paused for working on landing page
